name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: false
        description: The name of the artefact to deploy
        default: dist
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    # some-secret:
    # required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-output
        run: echo "step-result=Deployment successful" >> $GITHUB_OUTPUT
